# Generated by Django 4.0 on 2022-01-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reflect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('ref_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflect.reflectproblem')),
            ],
        ),
    ]
